import { app, BrowserWindow, ipcMain, shell } from 'electron';
import path from 'path';
import fs from 'fs';
import {
  Input,
  Output,
  BufferTarget,
  Conversion,
  BlobSource,
  Mp3OutputFormat,
  ALL_FORMATS,
  Mp4OutputFormat,
  canEncodeAudio,
} from 'mediabunny';
import { fixZoomWavHeader, identifyTrueFileFormat } from './utils/common';
import { registerMp3Encoder } from '@mediabunny/mp3-encoder';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;



let currentConversion: Conversion | null = null;

// output.target.buffer contains the final file

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 600,
    width: 800,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
// app.on('ready', createWindow);

app.whenReady().then(() => {
  createWindow();
  // 1. Audio Processing Handler (Convert & Tag)
  ipcMain.handle('process-audio', async (event, { filePath, tags }: { filePath: string; tags: { title: string; artist: string } }) => {

    if (!(await canEncodeAudio('mp3'))) {
      // Only register the custom encoder if there's no native support
      registerMp3Encoder();
    }

    identifyTrueFileFormat(filePath);

    // if (fixZoomWavHeader(filePath)) {
    //   console.log("Zoom WAV header fixed successfully.");
    // } else {
    //   console.warn("Failed to fix Zoom WAV header. The file may still be processed, but results could be unpredictable.");
    // }

    try {
      const bytes = await fs.promises.readFile(filePath);
      const source = new BlobSource(new Blob([bytes]));

      const input = new Input({
        source,
        formats: ALL_FORMATS,
      });
      const output = new Output({
        target: new BufferTarget(),
        format: new Mp3OutputFormat(),
      });

      currentConversion = await Conversion.init({
        input, output, tags: {
          title: tags.title,
          artist: tags.artist,
        },
      });

      if (!currentConversion.isValid) {
        // Conversion is invalid and cannot be executed without error.
        // This field gives reasons for why tracks were discarded:
        currentConversion.discardedTracks; // => DiscardedTrack[]

        console.info(currentConversion.discardedTracks);
        throw new Error('Conversion is invalid and cannot be executed; see the console for more.');

      }

      currentConversion.onProgress = (progress: number) => {
        console.log(`Conversion progress: ${progress}%`);
      };

      await currentConversion.execute();

      const originalName = path.basename(filePath) || 'output';
      const outputFileName = `${path.parse(originalName).name}.mp3`;

      // Return success, the full file path, and the parent folder directory
      return { hasErrors: false, fileBuffer: output.target.buffer, fileName: outputFileName };
    } catch (error: any) {

      console.log(error);

      await currentConversion?.cancel();

      return { hasErrors: true, error: error.message };
    }
  });

  // 2. Save arraybuffer to disk and open folder handler
  ipcMain.handle('save-and-open', async (event, fileBuffer: ArrayBuffer, fileName: string) => {
    try {
      // 1. Speicherort definieren (hier: Der Standard-Downloads-Ordner des Nutzers)
      const downloadsPath = app.getPath('downloads');
      const fullFilePath = path.join(downloadsPath, fileName);

      // 2. Den ArrayBuffer aus dem Frontend in einen Node.js Buffer umwandeln
      const nodeBuffer = Buffer.from(fileBuffer);

      // 3. Datei auf die Festplatte schreiben
      fs.writeFileSync(fullFilePath, nodeBuffer);

      // 4. Den Ordner öffnen und die frisch gespeicherte Datei hervorheben!
      shell.showItemInFolder(fullFilePath);

      return { hasErrors: false };

    } catch (error: any) {
      console.error("Fehler beim Speichern der Datei:", error);
      return { hasErrors: true, error: error?.message || 'Failed to save file' };
    }
  });

  // 3. Save file to a temporary folder and return its path
  ipcMain.handle('save-temp-file', async (event, buffer: ArrayBuffer, fileName: string) => {
    const tempDir = app.getPath('temp');
    const tempFilePath = path.join(tempDir, `rbtc-${Date.now()}-${fileName}`);
    await fs.promises.writeFile(tempFilePath, Buffer.from(buffer));
    return tempFilePath;
  });

  // 4. Delete a temporary file
  ipcMain.handle('delete-temp-file', async (event, filePath: string) => {
    try {
      await fs.promises.unlink(filePath);
    } catch {
      // Ignore if already deleted
    }
  });
});



// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});
