---
version: "3.8"

services:
  redis:
    command: redis-server /usr/local/etc/redis/redis.dev.conf
    volumes:
      # Configuration stored in the 'config' folder
      - ./config/redis.dev.conf:/usr/local/etc/redis/redis.dev.conf

  node-api:
    environment:
      # Override to development
      - NODE_ENV=development
