---
name: CI

on:
  push:
    branches-ignore:
      - master

jobs:
  docs-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install modules
        run: npm install
        working-directory: docs

      - name: Run tsc
        run: npm run typecheck
        working-directory: docs

  electron-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Install modules
        run: npm install

      - name: Run lint
        run: npm run lint

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: '22'
          package-manager-cache: false

      - name: Install modules
        run: npm install

      - name: Run unit tests with coverage
        run: npm run test:coverage

  electron-build:
    name: Run Electron Forge Make
    needs:
      - electron-lint
      - unit-tests
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
        arch:
          - x64
        include:
          - os: macos-latest
            arch: arm64
          - os: ubuntu-24.04-arm
            arch: armv7l
          - os: ubuntu-24.04-arm
            arch: arm64
          - os: windows-latest
            arch: ia32
    runs-on: "${{ matrix.os }}"
    steps:
      - run: git config --global core.autocrlf input
      - name: Checkout
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          package-manager-cache: false
      - run: npm install --immutable

      - name: Build (macOS)
        if: ${{ startsWith(matrix.os, 'macos-') }}
        run: npm run make

      - name: Build (Windows)
        if: ${{ startsWith(matrix.os, 'windows-') }}

        run: npm run make

      - name: Build (Linux)
        if: ${{ startsWith(matrix.os, 'ubuntu-') }}
        run: npm run make
